### ISSUE TITLE
Update Readme with build information

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/ARD#115]
Readme file needs an update.
The following information can be updated/added

- Android build req info to be updated
- Add info about building with coverage test,

`./gradlew clean build connectedCheck`
for coverage ->
`./gradlew clean build coverage`
Include info about where coverage reports are saved (app/build/reports/jacoco/../index,html

**Comment by kukreja-vikramaditya** [comment]
Also in this PR, update the PULL_REQUEST file point no 5. should be changed to `Follow same pattern as commit message`

**Comment by Rushi98** [comment]
Also, Line separator in `.github/CONTRIBUTING.md` is `/r/n` differs than project default (`/n`), this can also be done in this PR.

**Comment by kukreja-vikramaditya** [comment]
Too vague and suggestions completed in #149
