### ISSUE TITLE
Add check for google play services

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/ARD#141]
https://firebase.google.com/docs/cloud-messaging/android/client

Will ensure users without google PS won't have app crashes.
Proper testing will also be required to ensure tests don't fail

**Comment by aayushsingla** [comment]
shall i work on this @kukreja-vikramaditya ?

**Comment by kukreja-vikramaditya** [comment]
Actually i am not sure if this is valid?

**Comment by Rushi98** [comment]
​I think it is. @Vikram, remember issue with Sir's phone?​

**Comment by kukreja-vikramaditya** [comment]
How would we test this? Or should we be on the safe side and just add this code? (probably to BaseActivity?

**Comment by Rushi98** [comment]
IMO, `HomeActivity`. We'll create a shared pref entry to see whether this check has been done earlier so as to avoid running it repeatedly. (Ideally, it should be `LoginActivity` as it's first activity user sees after install. But since we have some users who are also logged in, `LoginActivity` code won't work for them.)

**Comment by kukreja-vikramaditya** [comment]
Yes but is there a possibilty that a notification is sent from the app that opens a different activity but Google Play was uninstalled between the Login and opening of this activity from a notification. Or are we sure that the notification would not trigger?

**Comment by Rushi98** [comment]
Nobody uninstalls Google Play

**Comment by kukreja-vikramaditya** [comment]
Ok any extra checks to ensure app works correctly is fine with me.
So check required in MainActivity

**Comment by kukreja-vikramaditya** [comment]
Merged
