### ISSUE TITLE
eval $CMD not exiting properly in case of an error 

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/ARD#146]
From https://travis-ci.org/MobileApplicationsClub/ARD/jobs/267489823#L3221
the command $CMD failed, but if was not marked as an error and build was passed.

**Comment by shreyasnbhat** [comment]
Critical it seems. Kaam karle pehle tu.

**Comment by kukreja-vikramaditya** [comment]
Has been resolved in travis yml in #153
