### ISSUE TITLE
Add complete git workflow

### ISSUE THREAD

**Issue by Rushi98** [MobileApplicationsClub/ARD#147]
In README.md or in a new file. This will be based this -

![screenshot from 2017-08-26 07-11-31](https://user-images.githubusercontent.com/16462824/29737708-4f92dcc0-8a30-11e7-92af-6ae580e8504f.png)

**Comment by kukreja-vikramaditya** [comment]
Could you resolve this issue?
Also as per https://github.com/MobileApplicationsClub/ARD/issues/115#issuecomment-312457016 please change `crlf` -> `lf`

**Comment by Rushi98** [comment]
yes

**Comment by Rushi98** [comment]
on it

**Comment by kukreja-vikramaditya** [comment]
Merged
