### ISSUE TITLE
Hide appbar in landscape orientation

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/ARD#182]
On mobile devices, need to hide the app bar layout as it takes up major space.

Further improvements ->

calculate whether to show app bar or not depending on available space(eg. tablets have more space)

**Comment by Rushi98** [comment]
invalid?

**Comment by kukreja-vikramaditya** [comment]
no

**Comment by aayushsingla** [comment]
@kukreja-vikramaditya  this issue is already fixed.Please close this now.
