### ISSUE TITLE
Admin description hidden in NewChatActivity

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/ARD#183]
Admin status is hidden . It shows momentarily and then goes away.

**Comment by Rushi98** [comment]
Admins and users have same class in realm therefore are in same table. We're using same key in both nodes. Hence `user.onDataChange()`  overrides data obtained in `admin.onDataChange()`. This can be corrected by 3 ways -
1. remove admins from user list 
2. use different key for same user in 2 lists
3. use different `admin` class

IMO, we should do 1.

**Comment by kukreja-vikramaditya** [comment]
Fixed.
