### ISSUE TITLE
Crash on log out

### ISSUE THREAD

**Issue by Rushi98** [MobileApplicationsClub/ARD#230]
Reinstall, Login, go straight to details and logout quickly to reproduce.
Due to https://github.com/MobileApplicationsClub/ARD/blob/chat/app/src/main/java/com/macbitsgoa/ard/fragments/DetailsFragment.java#L210

**Comment by kukreja-vikramaditya** [comment]
Slide was deleted by be earlier. Perhaps you did not do a Rebuild since then. Anyways i have have merged the pr
