### ISSUE TITLE
Add About ARD section

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/ARD#54]
Create an about page for ARD . 
More info here http://bits-pilani.ac.in/goa/ard/ard

**Comment by kukreja-vikramaditya** [comment]
On it

**Comment by kukreja-vikramaditya** [comment]
We could link to a static page on ard-bits.firebaseapp.com
@Rushi98 suggestions?

**Comment by kukreja-vikramaditya** [comment]
And suggestions for #53 ? 

For ARD should we simply link to their website?

**Comment by Rushi98** [comment]
1. A convenient option will be to fetch link from a firebase node.

2. Otherwise, any link that we have control can be used to redirect to other link.
https://en.wikipedia.org/wiki/Meta_refresh

However, I'd prefer the former (1).

**Comment by kukreja-vikramaditya** [comment]
Yes but that means we need to fetch from firebase. If we do (2), we could create a html page in hosting and redirect it. That would be easier. We will have a ready made link like (ard-bits.firebaseapp.com/ard) which will instantly redirect to set page in js

**Comment by kukreja-vikramaditya** [comment]
Redirect is available at 

[ard-bits.firebaseapp.com/ard](url)
and
[ard-bits.firebaseapp.com/ard.html](url)

**Comment by kukreja-vikramaditya** [comment]
Fixed f0fd1d3ad03cfc82ce1b9c081a616a82dba3f400
