### ISSUE TITLE
Add custom notification service for Firebase

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/ARD#55]
Firebase notification have very limited use and thus we need to create our own service to handle detailed notifications.. This service class should be able to handle simple, bigtext, bigimage notifications etc.. in the json file that we send to firebase server, appropriate keys should be used
Also this service should be placed inside **services** package

Example usage - https://github.com/MobileApplicationsClub/DoJMA/blob/master/app/src/main/java/com/csatimes/dojma/services/HandleFirebaseMessages.java
example body of json file sent to firebase server (this whole thing should be customised)
```json
{
    "data": {
    	"id" : "4422",
        "type" : "1",
        "smallTitle" : "DoJMA v2",
        "smallSubTitle" : "Update now from Google Play Store",
        "ticker" : "New update for DoJMA",
        "contentInfo" : "",
		"link" : "https://photo2.tinhte.vn/data/avatars/l/1885/1885712.jpg?1402763583",
        "className" : "HomeActivity",
        "page" : "2",
        "bigTitle" : "DoJMA Android app version 2 released!",
        "bigSubTitle" : "Hi folks! New DoJMA update is here! Major redesigning and improvements! This app was made by the Mobile App Club.They work really hard man...and get good products",
        "bigSummaryText" : "Update now"
     },
    "registration_ids": ["dQYmpLUACXQ:APA91bGl-NoIMJ2_DcctF5-OA8ghyWuyrMfsz3uhlj1BySl6axkAsmv5y_7YGfpQQJ2E0lP_fTcxpHpZdkJzY1tbcWA36e78ooxC_b0a1PAank9gFIAUHVZkHKmZT70MPZosCgvRlVfq","dfLXnRI36qY:APA91bFyjLblijVIjGLCGWVeB1B0z5j_3TYqRytJ-8hvuUESpDlX59gWF3hU-I-kA4VrRCPpEVFWl18ZarnPjqxxtZgFkVxoLr77HRex27VN7Mh3xupWykmKq_nnVIlVzrODKwKI7ktM"]
}
```

**Comment by hardik124** [comment]
i want to work on this issue

**Comment by kukreja-vikramaditya** [comment]
@hardik124 You need to figure out all possible types of supported Notifications and also provide fields to edit each and every part of them

**Comment by hardik124** [comment]
@kukreja-vikramaditya  , can you please elaborate?
And what keys are required for ARD app?
What will this service be used for?

**Comment by kukreja-vikramaditya** [comment]
Have a look at Notification Compat Builder https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html
And firebase notification and data message docs https://firebase.google.com/docs/cloud-messaging/android/client

The aim is to send custom notification messages(eg. Json above) using a rest api client like postman to firebase which will forward it to other users.

This notif from firebase to user will then be handled by the HandleFirbaseMessageService and according take action of creating notifications..

Depending on the data in the message, different kinds​of notification should be supported..eg BigTextNotification, BigImageNotification...etc

Along with unit tests for the app.

You can divide this issue into subparts like the HomeFragment issues.
Eg first support​ simple messages .. then go to more complex notification etc

_Sent from my LENOVO Lenovo K50a40 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Nirvan101** [comment]
dem memories...  :'(

**Comment by kukreja-vikramaditya** [comment]
Sorry
