### ISSUE TITLE
Change option for  LITERAL_FOR and LITERAL_WHILE token in RightCurly module in checkstyle

### ISSUE THREAD

**Issue by Rushi98** [MobileApplicationsClub/ARD#69]
A for loop doesn't have associated block after it but ```RightCurly``` errors

> '}' at column 13 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else, do/while or try/catch/finally). 

Should the token ```LITERAL_FOR``` be in RightCurly?

**Comment by kukreja-vikramaditya** [comment]
Fix is merged
