### ISSUE TITLE
FAQ Fragment development

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/ARD#78]
I have the following in mind -> 

when the user clicks on `FAQ` bottom nav button,

the resulting fragment can have sub  sections, eg. General, new, recently updated or something more specific as per ARD's req

on opening these sub sections, their related data will be shown (a fragment will replace the FAQ fragment) where https://material.uplabs.com/posts/quzica-question-answer-ui-concept can be followed

@MobileApplicationsClub/ard request your suggestions before approving this

**Comment by yashsharan** [comment]
The idea sounds good to me ..Regarding the UI go here https://oneplusstore.in/support/faq and see the animation when you hover under the accessory section.we could have a similar drop down feature for the FAQs in which when you click on the topic it would show a similar animation and show the queries regarding that topic

**Comment by kukreja-vikramaditya** [comment]
On it

**Comment by kukreja-vikramaditya** [comment]
I am thinking of having a viewpager with fragments..a common pattern in Google+ app
Under each fragment we can hv the FAQs
