### ISSUE TITLE
Home Fragment development

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/ARD#79]
there will be a recyclerview which will have heterogeneous items in it (and a date sticky label also).
Contents of the fragment can be filled later..
See TypeItem and SearchActivity in DoJMA for better understanding of het. recyclerview

@MobileApplicationsClub/ard

**Comment by kukreja-vikramaditya** [comment]
We also need to have a separate but easy to access imp link/dates/info sections. should we have a tablayout inside the HomeFragment?

**Comment by Nirvan101** [comment]
How do we use a fragment here? That's not clear from the DoJMA code. Won't we just have an activity with a  recyclerView of cards? Why do we have to use fragments here?

**Comment by Nirvan101** [comment]
im on it

**Comment by kukreja-vikramaditya** [comment]
On it

**Comment by kukreja-vikramaditya** [comment]
Merged. Will introduce auth in later issues
