### ISSUE TITLE
HF Card 2 - Simple Image and Title

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/ARD#81]
Simple image view with title/date..
On clicking it, a new activity should be loaded that may contain comments etc, and a possibility to enlarge image.
If post has some link also, show that on main card and inside activity also

**UPDATE**
The card in the RV should have a small icon with the number of comments right next to it

**Comment by Nirvan101** [comment]
im on it.

**Comment by kukreja-vikramaditya** [comment]
@Nirvan101 Please resolve #79 before starting this. I hv approved that issue
