### ISSUE TITLE
Add chrome custom tab

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/ARD#89]
https://developer.chrome.com/multidevice/android/customtabs

**Comment by yashsharan** [comment]
This issue would be done after the cards have been created right?

**Comment by kukreja-vikramaditya** [comment]
No there is no relation. this can be handled without the cards

**Comment by Nirvan101** [comment]
Some more information needed. Custom tab for what feature and leading where? What exactly do we have to implement?

**Comment by yashsharan** [comment]
It is used instead of webview as it is much faster.. Basically used to open any kind of link of website within the app

**Comment by Nirvan101** [comment]
Yes I read it up. I mean where should this code be written? The code to open a url using custom tabs isn't much, so it can be written at the place we want to open the browser. In which part of our code do we need to implement this?

**Comment by Rushi98** [comment]
Maybe create a utility class with those functions modified to our need.

**Comment by yashsharan** [comment]
Have a look at this https://github.com/GoogleChrome/custom-tabs-client/blob/master/Using.md
You would be using it at places where you have to open a link in place of webview.For now we havent created any card where the link needs to be opened so this issue can be done after the card has been created.

**Comment by Rushi98** [comment]
On it

**Comment by kukreja-vikramaditya** [comment]
Merged
