### ISSUE TITLE
Update firebase

### ISSUE THREAD

**Issue by Rushi98** [MobileApplicationsClub/ARD#92]
New version of firebase ```11.0.0``` has been [released](https://firebase.google.com/support/release-notes/android). We should update it for our project.

**Comment by Rushi98** [comment]
I'm on it.

**Comment by Rushi98** [comment]
Also updates are available for

- [ ] [build tools](https://developer.android.com/studio/releases/build-tools.html) version `26.0.0`.
- [ ] [checkstyle](http://checkstyle.sourceforge.net/releasenotes.html#Release_7.8.1) `7.8.1`
- [ ] [support library](https://developer.android.com/topic/libraries/support-library/revisions.html) `25.4.0`
- [ ] [Realm](https://realm.io/docs/java/latest/) `3.3.1`

I'm updating all to check if anything breaks. @kukreja-vikramaditya which of these should be updated?

**Comment by kukreja-vikramaditya** [comment]
Checkstyle and Realm are unrelated to the issue.
I am fine with support library and google play services (if they are req ofc)
Not so sure about build tools. if compatibility breaks, we shall see..restrict urself to Support Library and anything specific to this issue.

As far as Realm is concerned, it gets updated very often..We can do this later

**Comment by Rushi98** [comment]
I was getting ```FirebaseApiNotAvailableException``` in solving issue #43 . The only solution I found on StackOverflow were to update firebase and google play auth.

Also nothing broke!
